import { Plugin } from "@utils/pluginBase"; import { getPrefixes } from "@utils/pluginManager"; import { Api } from "teleproto"; import * as fs from "fs/promises"; import path from "path"; import axios from "axios"; import { createDirectoryInAssets } from "@utils/pathHelpers";   

const pfx = getPrefixes(); const mp = pfx[0];
const DD = createDirectoryInAssets("checkapi"); const KF = path.join(DD, "keys.json");

interface SK { name: string; key: string; baseUrl?: string; provider?: string; addedAt: number; }
async function lk(): Promise<SK[]> { try { await fs.mkdir(DD,{recursive:true}); return JSON.parse(await fs.readFile(KF,"utf8")); } catch { return []; } }
async function sk(k: SK[]): Promise<void> { await fs.mkdir(DD,{recursive:true}); await fs.writeFile(KF,JSON.stringify(k,null,2),"utf8"); }
function mk(k: string): string { return k.length<=8?"***":k.slice(0,7)+"..."+k.slice(-4); }
function isUrl(s: string): boolean { return /^(https?:\/\/|.+\.[a-z]{2,}(?:\/|$|:\d+)|.+\/v\d)/i.test(s) || s.includes("://"); }
function nu(s: string): string { let u=s.trim(); if(!/^https?:\/\//i.test(u)) u="https://"+u; return u.replace(/\/+$/,""); }

interface PI { provider: string; displayName: string; baseUrl: string; chatUrl: string; confidence: "high"|"medium"|"low"; headers: Record<string,string>; }
function dp(key: string, baseUrl?: string): PI {
  const t=key.trim();
  if(baseUrl){ const u=baseUrl.replace(/\/+$/,""); const h: Record<string,string>={}; if(u.includes("openrouter"))h["HTTP-Referer"]="https://t.me/telebox_next"; const g=u.includes("generativelanguage")||u.includes("googleapis"); return { provider:"custom",displayName:`自定义 (${new URL(u).hostname})`,baseUrl:u,chatUrl:g?`${u}/v1beta/models/gemini-2.0-flash:generateContent`:`${u}/v1/chat/completions`,confidence:"medium",headers:h }; }
  if(/^sk-ant-/i.test(t))return{provider:"anthropic",displayName:"Anthropic",baseUrl:"https://api.anthropic.com",chatUrl:"https://api.anthropic.com/v1/messages",confidence:"high",headers:{"x-api-key":t,"anthropic-version":"2023-06-01","content-type":"application/json"}};
  if(/^sk-or-v1-/i.test(t))return{provider:"openrouter",displayName:"OpenRouter",baseUrl:"https://openrouter.ai/api/v1",chatUrl:"https://openrouter.ai/api/v1/chat/completions",confidence:"high",headers:{Authorization:`Bearer ${t}`,"HTTP-Referer":"https://t.me/telebox_next"}};
  if(/^sk-/i.test(t))return{provider:t.length<40?"deepseek":"openai",displayName:t.length<40?"DeepSeek":"OpenAI",baseUrl:t.length<40?"https://api.deepseek.com":"https://api.openai.com",chatUrl:t.length<40?"https://api.deepseek.com/v1/chat/completions":"https://api.openai.com/v1/chat/completions",confidence:t.length<40?"medium":"high",headers:{Authorization:`Bearer ${t}`}};
  if(/^xai-/i.test(t))return{provider:"xai",displayName:"xAI (Grok)",baseUrl:"https://api.x.ai",chatUrl:"https://api.x.ai/v1/chat/completions",confidence:"high",headers:{Authorization:`Bearer ${t}`}};
  if(/^AIza/i.test(t))return{provider:"gemini",displayName:"Google Gemini",baseUrl:"https://generativelanguage.googleapis.com",chatUrl:"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent",confidence:"high",headers:{}};
  if(t.length>20)return{provider:"openai",displayName:"OpenAI（推测）",baseUrl:"https://api.openai.com",chatUrl:"https://api.openai.com/v1/chat/completions",confidence:"low",headers:{Authorization:`Bearer ${t}`}};
  return{provider:"unknown",displayName:"未知",baseUrl:"",chatUrl:"",confidence:"low",headers:{}};
}

interface AR { ok:boolean; data?:unknown; status?:number; error?:string; headers?:Record<string,string>; elapsedMs?:number; }
async function ag(url:string,hdrs:Record<string,string>,tms=15000): Promise<AR>{const s=Date.now();try{const r=await axios.get(url,{headers:hdrs,timeout:tms,validateStatus:()=>true});const e=Date.now()-s;const a:AR={ok:r.status>=200&&r.status<300,data:r.data,status:r.status,elapsedMs:e};const h:Record<string,string>={};for(const[k,v]of Object.entries(r.headers as Record<string,string>||{})){if(/rate.?limit|retry.?after|x-ratelimit/i.test(k))h[k]=String(v);}if(Object.keys(h).length)a.headers=h;if(!a.ok)a.error=`HTTP ${r.status}: ${JSON.stringify(r.data).slice(0,200)}`;return a;}catch(e:unknown){return{ok:false,error:ge(e)||String(e),elapsedMs:Date.now()-s};}}
async function ap(url:string,hdrs:Record<string,string>,body:unknown,tms=30000): Promise<AR>{const s=Date.now();try{const r=await axios.post(url,body,{headers:hdrs,timeout:tms,validateStatus:()=>true});const e=Date.now()-s;const a:AR={ok:r.status>=200&&r.status<300,data:r.data,status:r.status,elapsedMs:e};const h:Record<string,string>={};for(const[k,v]of Object.entries(r.headers as Record<string,string>||{})){if(/rate.?limit|retry.?after|x-ratelimit/i.test(k))h[k]=String(v);}if(Object.keys(h).length)a.headers=h;if(!a.ok){const d=r.data as Record<string,unknown>|undefined;a.error=d?.error&&typeof d.error==="object"?String((d.error as Record<string,unknown>).message||JSON.stringify(d.error)):`HTTP ${r.status}: ${JSON.stringify(r.data).slice(0,200)}`;}return a;}catch(e:unknown){return{ok:false,error:ge(e)||String(e),elapsedMs:Date.now()-s};}}
function fh(h?:Record<string,string>):string{if(!h||!Object.keys(h).length)return"";const l:string[]=[];for(const[k,v]of Object.entries(h)){l.push(`  ⚡ ${k.replace(/^x-ratelimit-/i,"").replace(/-/g," ")}: ${v}`);}return l.join("\n");}

interface CTR { ok:boolean; text?:string; model?:string; usage?:{prompt:number;completion:number;total:number}; elapsedMs?:number; error?:string; headers?:Record<string,string>; }
async function ct(provider:string,key:string,baseUrl:string,askText?:string): Promise<CTR>{const q=askText||"say 'ok' in one word";const info=dp(key,baseUrl);
  if(provider==="gemini"){const url=baseUrl.includes("v1beta")?`${baseUrl}/models/gemini-2.0-flash:generateContent`:`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent`;const params=baseUrl.includes("generativelanguage")?`?key=${key}`:"";const r=await ap(`${url}${params}`,{"content-type":"application/json"},{contents:[{parts:[{text:q}]}],generationConfig:{maxOutputTokens:50,temperature:0}},20000);if(r.ok){const d=r.data as Record<string,unknown>|undefined;const cs=d?.candidates as Array<Record<string,unknown>>|undefined;const ct=cs?.[0]?.content as Record<string,unknown>|undefined;const ps=ct?.parts as Array<Record<string,string>>|undefined;const tx=ps?.map(p=>p.text||"").join("")||"";const u=d?.usageMetadata as Record<string,number>|undefined;return{ok:true,text:tx,model:"gemini-2.0-flash",usage:u?{prompt:u.promptTokenCount||0,completion:u.candidatesTokenCount||0,total:u.totalTokenCount||0}:undefined,elapsedMs:r.elapsedMs,headers:r.headers};}return{ok:false,error:r.error,elapsedMs:r.elapsedMs};}
  if(provider==="anthropic"){const r=await ap(info.chatUrl,{"x-api-key":key,"anthropic-version":"2023-06-01","content-type":"application/json"},{model:"claude-3-5-haiku-latest",max_tokens:50,messages:[{role:"user",content:q}]},20000);if(r.ok){const d=r.data as Record<string,unknown>|undefined;const ct=(d?.content as Array<Record<string,unknown>>|undefined)?.[0];const tx=String(ct?.text||"");const u=d?.usage as Record<string,number>|undefined;return{ok:true,text:tx,model:String(d?.model||"claude"),usage:u?{prompt:u.input_tokens||0,completion:u.output_tokens||0,total:(u.input_tokens||0)+(u.output_tokens||0)}:undefined,elapsedMs:r.elapsedMs,headers:r.headers};}return{ok:false,error:r.error,elapsedMs:r.elapsedMs};}
  const mm:Record<string,string>={openai:"gpt-4o-mini",deepseek:"deepseek-chat",openrouter:"openai/gpt-4o-mini",xai:"grok-2-latest",custom:"gpt-4o-mini"};const model=mm[provider]||"gpt-4o-mini";
  const r=await ap(info.chatUrl,{"content-type":"application/json",...(provider==="openrouter"?{Authorization:`Bearer ${key}`,"HTTP-Referer":"https://t.me/telebox_next"}:{Authorization:`Bearer ${key}`})},{model,messages:[{role:"user",content:q}],max_tokens:50,temperature:0},20000);
  if(r.ok){const d=r.data as Record<string,unknown>|undefined;const cs=d?.choices as Array<Record<string,unknown>>|undefined;const tx=String((cs?.[0]?.message as Record<string,unknown>|undefined)?.content||cs?.[0]?.text||"");const u=d?.usage as Record<string,number>|undefined;return{ok:true,text:tx.trim(),model:String(d?.model||model),usage:u?{prompt:u.prompt_tokens||0,completion:u.completion_tokens||0,total:u.total_tokens||0}:undefined,elapsedMs:r.elapsedMs,headers:r.headers};}return{ok:false,error:r.error,elapsedMs:r.elapsedMs};}

async function lmf(provider:string,key:string,baseUrl:string,compact=false): Promise<string>{const info=dp(key,baseUrl);const url=provider==="gemini"?`https://generativelanguage.googleapis.com/v1beta/models?key=${key}`:provider==="anthropic"?`${info.baseUrl}/v1/models`:`${info.baseUrl}/v1/models`;const r=await ag(url,provider==="anthropic"?info.headers:{...info.headers,Authorization:`Bearer ${key}`},12000);if(!r.ok)return`❌ 获取模型失败: ${r.error}`;let models:Array<Record<string,unknown>>=[];if(provider==="gemini"){models=(r.data as Record<string,unknown>|undefined)?.models as Array<Record<string,unknown>>||[];}else{const d=r.data as Record<string,unknown>|undefined;models=(Array.isArray(r.data)?r.data:d?.data as Array<Record<string,unknown>>)||[];}if(!models.length)return"❌ 模型列表为空";const cats:Record<string,string[]>={};let total=0;for(const m of models){const name=String(m.id||m.name||"").replace("models/","");if(!name)continue;const owner=String(m.owned_by||"");let cat="其他";if(provider==="gemini"){cat=name.includes("gemini")?"Gemini":name.includes("embedding")?"Embedding":name.includes("imagen")?"Imagen":"其他";}else{if(/gpt|o1|o3|o4/i.test(name))cat="GPT / o-series";else if(/claude/i.test(name))cat="Claude";else if(/gemini/i.test(name))cat="Gemini";else if(/deepseek/i.test(name))cat="DeepSeek";else if(/grok/i.test(name))cat="Grok";else if(/llama|mistral|mixtral|qwen/i.test(name))cat="开源模型";else if(/embed|text-embed/i.test(name))cat="Embedding";else if(/dall-e|imagen|flux|stable/i.test(name))cat="图像生成";else if(/tts|whisper|audio/i.test(name))cat="语音";else if(/moderation/i.test(name))cat="审核";else if(owner)cat=owner;}(cats[cat]||=[]).push(name);total++;}const lines:string[]=[];lines.push(`🤖 可用模型: ${total} 个`);const cn=Object.keys(cats).sort((a,b)=>(cats[b].length-cats[a].length)||a.localeCompare(b));for(const cat of cn){const ms=cats[cat];if(compact&&cn.length>1&&ms.length<3)continue;lines.push(`\n<b>${cat}</b> (${ms.length}):`);lines.push(`<blockquote expandable>${ms.slice(0,12).map(m=>`<code>${m}</code>`).join(" | ")}${ms.length>12?` | ... +${ms.length-12}`:""}</blockquote>`);}if(r.headers&&Object.keys(r.headers).length){lines.push(`\n⚡ 速率限制:`);for(const[k,v]of Object.entries(r.headers)){lines.push(`  <code>${k}</code>: ${v}`);}}return lines.join("\n");}

async function cb(provider:string,key:string,baseUrl:string): Promise<string>{const hdrs:Record<string,string>={Authorization:`Bearer ${key}`,...(provider==="openrouter"?{"HTTP-Referer":"https://t.me/telebox_next"}:{})};const lines:string[]=[];
  if(provider==="openai"){const sub=await ag(`${baseUrl}/v1/dashboard/billing/subscription`,hdrs,10000);if(sub.ok){const d=sub.data as Record<string,unknown>|undefined;const plan=(d?.plan as Record<string,unknown>|undefined)?.title||"?";const until=d?.access_until?new Date((d.access_until as number)*1000).toLocaleDateString("zh-CN"):"?";lines.push(`📋 套餐: ${plan} | 📅 至: ${until}`);lines.push(`💰 硬上限: $${d?.hard_limit_usd??"?"} | 软上限: $${d?.soft_limit_usd??"?"} | 系统: $${d?.system_hard_limit_usd??"?"}`);}else if(sub.status===401)return"❌ Key 无效";else lines.push("⚠️ 无 billing 权限");const now=Math.floor(Date.now()/1000);const usg=await ag(`${baseUrl}/v1/dashboard/billing/usage?start_date=${now-90*86400}&end_date=${now}`,hdrs,10000);if(usg.ok){const d=usg.data as Record<string,unknown>|undefined;lines.push(`📊 近 90 天: $${(((d?.total_usage as number)||0)/100).toFixed(4)}`);}if(sub.headers&&Object.keys(sub.headers).length)lines.push(fh(sub.headers));return lines.join("\n")||"✅ Key 有效";}
  if(provider==="openrouter"){const r=await ag(`${baseUrl}/auth/key`,hdrs,10000);if(r.ok){const d=(r.data as Record<string,unknown>|undefined);const info=(d?.data||d)as Record<string,unknown>|undefined||{};lines.push(`🏷️ ${info.label||info.name||"?"}`);lines.push(`💰 余额: $${info.credits??"?"} | 📊 已用: $${info.usage??"?"}${info.limit!==undefined?` | 📏 限额: $${info.limit}`:""}`);if(info.rate_limit){const rl=info.rate_limit as Record<string,unknown>;lines.push(`⚡ 速率: ${rl.requests||"?"} req / ${rl.interval||"?"}`);}}else if(r.status===401)return"❌ Key 无效";else return`⚠️ ${r.error||"查询失败"}`;if(r.headers&&Object.keys(r.headers).length)lines.push(fh(r.headers));return lines.join("\n");}
  if(provider==="deepseek"){const r=await ag(`${baseUrl}/user/balance`,hdrs,10000);if(r.ok){const d=r.data as Record<string,unknown>|undefined;lines.push(`✅ 可用: ${d?.is_available?"是":"否"}`);const infos=d?.balance_infos as Array<Record<string,unknown>>|undefined;if(infos)for(const bi of infos)lines.push(`💰 ${bi.currency||"余额"}: ${bi.total_balance||"?"} (已用: ${bi.topped_up_balance||"?"})`);}else if(r.status===401)return"❌ Key 无效";else return`⚠️ ${r.error||"查询失败"}`;return lines.join("\n");}
  if(provider==="anthropic"){const r=await ap("https://api.anthropic.com/v1/messages",{"x-api-key":key,"anthropic-version":"2023-06-01","content-type":"application/json"},{model:"claude-3-5-haiku-latest",max_tokens:1,messages:[{role:"user",content:"hi"}]},15000);if(r.status===401||r.status===403)return"❌ Key 无效";if(r.ok||r.status===429)return`✅ Key 有效 (${r.status===429?"已限流":"正常"})\n⚠️ Anthropic 无公开余额接口，请前往 console.anthropic.com 查看`;return`⚠️ HTTP ${r.status}: ${r.error||""}`;}
  if(provider==="gemini"){const r=await ag(`https://generativelanguage.googleapis.com/v1beta/models?key=${key}`,{},10000);if(r.ok){const ms=(r.data as Record<string,unknown>|undefined)?.models as Array<unknown>|undefined;return`✅ Key 有效 | 📋 ${ms?.length??0} 个模型\n⚠️ Gemini 免费额度请在 Google Cloud Console 查看`;}if(r.status===400&&JSON.stringify(r.data||"").includes("API_KEY_INVALID"))return"❌ Key 无效";return`⚠️ HTTP ${r.status}: ${r.error||"可能有效"}`;}
  if(provider==="xai"){const r=await ag(`${baseUrl}/v1/models`,hdrs,10000);if(r.ok){const arr=Array.isArray(r.data)?r.data:(r.data as Record<string,unknown>|undefined)?.data as Array<unknown>|undefined;return`✅ Key 有效 | 📋 ${arr?.length??0} 个模型\n⚠️ xAI 无公开余额接口，请前往 console.x.ai 查看`;}if(r.status===401)return"❌ Key 无效";return`⚠️ HTTP ${r.status}`;}
  const r=await ag(`${baseUrl}/v1/models`,hdrs,10000);if(r.ok){const arr=Array.isArray(r.data)?r.data:(r.data as Record<string,unknown>|undefined)?.data as Array<unknown>|undefined;return`✅ 连接成功 | 📋 ${arr?.length??"?"} 个模型\n🕐 ${r.elapsedMs||"?"}ms`;}if(r.status===401)return"❌ Key 无效";return`⚠️ HTTP ${r.status}: ${r.error||"无法连接"}`;}

async function fcv2(provider:string,key:string,baseUrl:string): Promise<string[]>{const rs:string[]=[];const info=dp(key,baseUrl);rs.push(`🔍 <b>${info.displayName}</b> (${info.provider}, ${info.confidence})`);rs.push(`🔑 ${mk(key)}`);rs.push(`\n💰 <b>余额/状态</b>:`);try{rs.push(await cb(provider,key,baseUrl));}catch(e:unknown){rs.push(`⚠️ 余额查询异常: ${ge(e)||e}`);}rs.push(`\n📋 <b>模型列表</b>:`);try{rs.push(await lmf(provider,key,baseUrl,true));}catch(e:unknown){rs.push(`⚠️ ${ge(e)||e}`);}rs.push(`\n💬 <b>对话测试</b>:`);try{const chat=await ct(provider,key,baseUrl);if(chat.ok){rs.push(`✅ 响应: "${chat.text}" (${chat.elapsedMs}ms)`);rs.push(`🤖 模型: <code>${chat.model}</code>`);if(chat.usage){rs.push(`📊 Token: 输入 ${chat.usage.prompt} | 输出 ${chat.usage.completion} | 合计 ${chat.usage.total}`);}if(chat.headers)rs.push(fh(chat.headers));}else{rs.push(`❌ 失败: ${chat.error||"无响应"}`);}}catch(e:unknown){rs.push(`⚠️ 对话测试异常: ${ge(e)||e}`);}return rs;}

function ge(e:unknown):string{const o=e as Record<string,unknown>;return String(o?.message||o?.stderr||e||"未知错误");}class CheckApiPlugin extends Plugin{name="checkapi";description=`🔍 API Key 全功能检测\n\n支持: OpenAI / Anthropic / Gemini / DeepSeek / OpenRouter / xAI / 自定义\n\n用法:\n<blockquote expandable><code>${mp}checkapi &lt;key&gt; [baseUrl]</code> — 一键全检 (余额+模型+对话测试)\n<code>${mp}checkapi &lt;baseUrl&gt; &lt;key&gt;</code> — URL 优先（自动识别 API）\n<code>${mp}checkapi ask &lt;key|name&gt; &lt;问题&gt;</code> — 真实对话\n<code>${mp}checkapi models &lt;key|name&gt;</code> — 模型列表 (分类折叠)\n<code>${mp}checkapi save &lt;name&gt; &lt;key|baseUrl&gt; &lt;key|baseUrl&gt;</code>\n<code>${mp}checkapi list</code> / <code>del &lt;name&gt;</code>\n<code>${mp}checkapi check &lt;name|all&gt;</code> — 检测已保存</blockquote>\n\n自动识别: sk- → OpenAI | sk-ant- → Anthropic | sk-or-v1- → OpenRouter | AIza → Gemini | xai- → xAI\n传 URL: <code>.checkapi https://my.api.com/v1 sk-xxx</code> 直接测任意兼容 API`;

cmdHandlers:Record<string,(msg: Api.Message) => Promise<void>>={checkapi:async(msg)=>{const text=msg.message.slice(mp.length).trim();const parts=text.split(/\s+/).filter(Boolean);if(parts.length===0||parts[0]==="help"){await msg.edit({text:`${this.description}`, parseMode: "html" });return;}const sub=parts[0]?.toLowerCase();
if(sub==="list"){const keys=await lk();if(!keys.length){await msg.edit({text:`📭 未保存\n<code>${mp}checkapi save &lt;name&gt; &lt;key&gt;</code>`, parseMode: "html" });return;}const lines=[`🔑 已保存 (${keys.length}):`];for(const k of keys)lines.push(`  • <b>${k.name}</b>: ${mk(k.key)} (${k.provider||"auto"})${k.baseUrl?` [${new URL(k.baseUrl).hostname}]`:""}`);await msg.edit({text:`${lines.join("\n")}`, parseMode: "html" });return;}
if(sub==="del"||sub==="delete"){const name=parts[1];if(!name){await msg.edit({text:`❌ <code>${mp}checkapi del &lt;name&gt;</code>`, parseMode: "html" });return;}const keys=await lk();const idx=keys.findIndex(k=>k.name===name);if(idx===-1){await msg.edit({text:`❌ 未找到 <b>${name}</b>`, parseMode: "html" });return;}keys.splice(idx,1);await sk(keys);await msg.edit({text:`✅ 已删除 <b>${name}</b>`, parseMode: "html" });return;}
if(sub==="save"){let name:string|undefined,key:string|undefined,baseUrl:string|undefined;if(parts.length>=4&&isUrl(parts[2])){name=parts[1];baseUrl=nu(parts[2]);key=parts[3];}else{name=parts[1];key=parts[2];baseUrl=parts[3];}if(!name||!key){await msg.edit({text:`❌ <code>${mp}checkapi save &lt;name&gt; &lt;key|baseUrl&gt; &lt;key|baseUrl&gt;</code>\n示例: <code>${mp}checkapi save oai sk-xxx</code>`, parseMode: "html" });return;}const keys=await lk();const info=dp(key,baseUrl);const entry:SK={name,key,baseUrl,provider:info.provider,addedAt:Date.now()};const idx=keys.findIndex(k=>k.name===name);if(idx>=0)keys[idx]=entry;else keys.push(entry);await sk(keys);await msg.edit({text:`✅ ${idx>=0?"已更新":"已保存"} <b>${name}</b> (${info.displayName})\n<code>${mp}checkapi ${name}</code> 检测`, parseMode: "html" });return;}
if(sub==="check"){const target=parts[1]||"all";if(target==="all"){const keys=await lk();if(!keys.length){await msg.edit({text:`📭 未保存`, parseMode: "html" });return;}await msg.edit({text:`🔍 检测 ${keys.length} 个...`, parseMode: "html" });const results:string[]=[];for(const k of keys){results.push(`\n━━━ <b>${k.name}</b> ━━━`);const info=dp(k.key,k.baseUrl);results.push(...(await fcv2(info.provider,k.key,k.baseUrl||info.baseUrl)));}await msg.edit({text:`${results.join("\n")}`, parseMode: "html" });return;}const keys=await lk();const found=keys.find(k=>k.name===target);if(!found){await msg.edit({text:`❌ 未找到 <b>${target}</b>`, parseMode: "html" });return;}await msg.edit({text:`🔍 <b>${target}</b>...`, parseMode: "html" });const info=dp(found.key,found.baseUrl);const results=await fcv2(info.provider,found.key,found.baseUrl||info.baseUrl);await msg.edit({text:`${results.join("\n")}`, parseMode: "html" });return;}
if(sub==="models"){const input=parts[1];if(!input){await msg.edit({text:`❌ <code>${mp}checkapi models &lt;key|name&gt;</code>`, parseMode: "html" });return;}const keys=await lk();const found=keys.find(k=>k.name===input);const key=found?found.key:input;const info=dp(key,found?.baseUrl);await msg.edit({text:`🔍 ${info.displayName} 模型列表...`, parseMode: "html" });const result=await lmf(info.provider,key,info.baseUrl);await msg.edit({text:`${result}`, parseMode: "html" });return;}
if(sub==="ask"){const input=parts[1];const question=parts.slice(2).join(" ");if(!input){await msg.edit({text:`❌ <code>${mp}checkapi ask &lt;key|name&gt; &lt;问题&gt;</code>`, parseMode: "html" });return;}const keys=await lk();const found=keys.find(k=>k.name===input);const key=found?found.key:input;const info=dp(key,found?.baseUrl);const prompt=question||"say hello in one word";await msg.edit({text:`💬 ${info.displayName}: "${prompt}" ...`, parseMode: "html" });const chat=await ct(info.provider,key,info.baseUrl,prompt);if(chat.ok){const lines=[`💬 <b>${info.displayName}</b> 真实对话`,`🤖 模型: <code>${chat.model}</code> | 🕐 ${chat.elapsedMs}ms`,`📝 回复: ${chat.text}`];if(chat.usage)lines.push(`📊 Token: 入 ${chat.usage.prompt} | 出 ${chat.usage.completion} | 计 ${chat.usage.total}`);if(chat.headers)lines.push(fh(chat.headers));await msg.edit({text:`${lines.join("\n")}`, parseMode: "html" });}else{await msg.edit({text:`❌ 失败 (${chat.elapsedMs||"?"}ms): ${chat.error||"无响应"}`, parseMode: "html" });}return;}
let key:string,baseUrl:string|undefined;let label:string;const keys=await lk();if(parts.length>=2&&isUrl(parts[0])){baseUrl=nu(parts[0]);key=parts[1];label=mk(key);}else if(parts.length>=2&&isUrl(parts[1])){key=parts[0];baseUrl=nu(parts[1]);const found=keys.find(k=>k.name===key);label=found?found.name:mk(key);key=found?found.key:key;}else{const input=parts[0];const found=keys.find(k=>k.name===input);key=found?found.key:input;baseUrl=found?.baseUrl;label=found?found.name:mk(key);}const info=dp(key,baseUrl);await msg.edit({text:`🔍 <b>${label}</b> (${info.displayName}) 全检中...`, parseMode: "html" });const results=await fcv2(info.provider,key,info.baseUrl);results.unshift(`🔍 <b>${label}</b>`);await msg.edit({text:`${results.join("\n")}`, parseMode: "html" });},};}

export default new CheckApiPlugin();
